In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Aarav", "Priya", "Rahul", "Sneha", "Vikram", "Ananya", "Rohan", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "HR"],
    "Age": [23, 25, 22, 28, 24, 21, 26, 23],
    "Marks": [85, 72, 91, 68, 79, 95, 74, 88],
    "Attendance": [92, 85, 96, 78, 88, 98, 82, 94]
}

df = pd.DataFrame(data)

df

     Name Department  Age  Marks  Attendance
0   Aarav         IT   23     85          92
1   Priya         HR   25     72          85
2   Rahul         IT   22     91          96
3   Sneha    Finance   28     68          78
4  Vikram         HR   24     79          88
5  Ananya         IT   21     95          98
6   Rohan    Finance   26     74          82
7    Neha         HR   23     88          94

In [3]:
print("Number of rows and columns:", df.shape)
print("\nColumn names:")
print(df.columns)

Number of rows and columns: (8, 5)

Column names:
Index(['Name', 'Department', 'Age', 'Marks', 'Attendance'], dtype='str')

In [4]:
marks_ascending = df.sort_values(by="Marks", ascending=True)

print("Students sorted by Marks in ascending order:")
marks_ascending

Students sorted by Marks in ascending order:

     Name Department  Age  Marks  Attendance
3   Sneha    Finance   28     68          78
1   Priya         HR   25     72          85
6   Rohan    Finance   26     74          82
4  Vikram         HR   24     79          88
0   Aarav         IT   23     85          92
7    Neha         HR   23     88          94
2   Rahul         IT   22     91          96
5  Ananya         IT   21     95          98

In [6]:
marks_descending = df.sort_values(by="Marks", ascending=False)

print("Students sorted by Marks in descending order:")
marks_descending

Students sorted by Marks in descending order:

     Name Department  Age  Marks  Attendance
5  Ananya         IT   21     95          98
2   Rahul         IT   22     91          96
7    Neha         HR   23     88          94
0   Aarav         IT   23     85          92
4  Vikram         HR   24     79          88
6   Rohan    Finance   26     74          82
1   Priya         HR   25     72          85
3   Sneha    Finance   28     68          78

In [7]:
department_ascending = df.sort_values(by="Department", ascending=True)

print("Students sorted by Department in ascending order:")
department_ascending

Students sorted by Department in ascending order:

     Name Department  Age  Marks  Attendance
3   Sneha    Finance   28     68          78
6   Rohan    Finance   26     74          82
1   Priya         HR   25     72          85
4  Vikram         HR   24     79          88
7    Neha         HR   23     88          94
0   Aarav         IT   23     85          92
2   Rahul         IT   22     91          96
5  Ananya         IT   21     95          98

In [8]:
department_descending = df.sort_values(by="Department", ascending=False)

print("Students sorted by Department in descending order:")
department_descending

Students sorted by Department in descending order:

     Name Department  Age  Marks  Attendance
0   Aarav         IT   23     85          92
2   Rahul         IT   22     91          96
5  Ananya         IT   21     95          98
1   Priya         HR   25     72          85
4  Vikram         HR   24     79          88
7    Neha         HR   23     88          94
3   Sneha    Finance   28     68          78
6   Rohan    Finance   26     74          82

In [9]:
multiple_sort = df.sort_values(
    by=["Department", "Marks"],
    ascending=[True, False]
)

print("Sorted by Department ascending and Marks descending:")
multiple_sort

Sorted by Department ascending and Marks descending:

     Name Department  Age  Marks  Attendance
6   Rohan    Finance   26     74          82
3   Sneha    Finance   28     68          78
7    Neha         HR   23     88          94
4  Vikram         HR   24     79          88
1   Priya         HR   25     72          85
5  Ananya         IT   21     95          98
2   Rahul         IT   22     91          96
0   Aarav         IT   23     85          92

In [10]:
attendance_marks_sort = df.sort_values(
    by=["Attendance", "Marks"],
    ascending=[False, False]
)

print("Sorted by Attendance and Marks in descending order:")
attendance_marks_sort

Sorted by Attendance and Marks in descending order:

     Name Department  Age  Marks  Attendance
5  Ananya         IT   21     95          98
2   Rahul         IT   22     91          96
7    Neha         HR   23     88          94
0   Aarav         IT   23     85          92
4  Vikram         HR   24     79          88
1   Priya         HR   25     72          85
6   Rohan    Finance   26     74          82
3   Sneha    Finance   28     68          78

In [11]:
print("Original Dataset:")
display(df)

print("\nDataset Sorted by Marks:")
display(marks_descending)

Original Dataset:

     Name Department  Age  Marks  Attendance
0   Aarav         IT   23     85          92
1   Priya         HR   25     72          85
2   Rahul         IT   22     91          96
3   Sneha    Finance   28     68          78
4  Vikram         HR   24     79          88
5  Ananya         IT   21     95          98
6   Rohan    Finance   26     74          82
7    Neha         HR   23     88          94

Dataset Sorted by Marks:

     Name Department  Age  Marks  Attendance
5  Ananya         IT   21     95          98
2   Rahul         IT   22     91          96
7    Neha         HR   23     88          94
0   Aarav         IT   23     85          92
4  Vikram         HR   24     79          88
6   Rohan    Finance   26     74          82
1   Priya         HR   25     72          85
3   Sneha    Finance   28     68          78

In [12]:
print("SORTING TASK COMPLETED")
print("----------------------")
print("1. Numerical column sorted in ascending order")
print("2. Numerical column sorted in descending order")
print("3. Categorical column sorted in ascending order")
print("4. Categorical column sorted in descending order")
print("5. Dataset sorted using multiple columns")

SORTING TASK COMPLETED
----------------------
1. Numerical column sorted in ascending order
2. Numerical column sorted in descending order
3. Categorical column sorted in ascending order
4. Categorical column sorted in descending order
5. Dataset sorted using multiple columns